### ISSUE TITLE
Implement the Solana Program Library (SPL)

### ISSUE THREAD

**Issue by hoakbuilds** [bmresearch/Solnet#99]
### Implement the following Solana Program Library on-chain programs:

- [x] Token Program ( #76 )
- [x] Token Swap Program ( #260 )
- [x] Associated Token Account Program ( #106 )
- [x] Memo Program
- [x] Name Service ( #101 ) 
- [x] Shared memory Program ( #105 )
- [ ] Stake Pool Program

### Update: 

After some thought we've decided not to include the Feature Proposal Program in our SPL implementation for v1

### Update 2:

Discarded program implementations.

Token-Lending Program ( #254 )

**Comment by murlokito** [comment]
Because the Token Lending Program isn't currently being used, rather, it's forks are, it will not be included in Solnet.Programs, this code has been moved to [Solnet.Reference.Implementations](https://github.com/bmresearch/Solnet.Reference.Implementations/) which is a different repo that will not be published to nuget. This is merely so that the implementation can be used as reference, the majority of the relevant code will be published under [Solnet.Solend](https://github.com/bmresearch/Solnet.Solend).
